import { AppProps, type AppType } from "next/app";
import { Inter } from "next/font/google";
import { SessionProvider } from "next-auth/react"
import "@/styles/globals.css";
import { Provider } from "react-redux";
import { store } from "@/redux/configstore";
import Head from "next/head";
import AuthProvider from "@/contexts/authContext";
import { Toaster } from "sonner";
// import Footer from "@/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

const MyApp: AppType = ({ 
  Component, 
  pageProps: { session, ...pageProps }, } : AppProps) => {
  return (
    // <SessionProvider session={session}>
    <AuthProvider>
      <Provider store={store}>
        <Head>
          <title>Ban học tập BCU</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="https://th.bing.com/th/id/OIP.5BFnewK6zvkgRdnSydN4fAHaF1?w=196&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7" />
        </Head>
        <main className={`font-jersey font-normal ${inter.variable}`}>
          <Component {...pageProps} />
        </main>
        <Toaster richColors/>
      </Provider>
    </AuthProvider>
    // </SessionProvider>
  );
};

export default MyApp;
