import Head from "next/head";
import Link from "next/link";
import Button from "@/components/common/Button";
import HomeComponent from "@/components/Home";
import { fetchAdmins } from "@/hooks/fetchAdmins";
import { useFetchSession } from "@/hooks/useSession";
import { useDispatch } from "react-redux";
import { useEffect } from "react";
import { setAuthAdmin } from "@/redux/Loading/authAdmin";
import AboutComponent from "@/components/About";
import { signIn } from "next-auth/react";
import Topbar from "@/components/Topbar";
import NavBar from "@/components/NavBar";

export default function Home() {
  let {admins} = fetchAdmins();
  let {session} = useFetchSession();
  const user = session?.user.email;
  const dispatch = useDispatch();
    
  if (admins.includes(user)) {
    dispatch(setAuthAdmin(true));
  }
  return (
    <>
      <Head>
        <title>Ban học tập BCU</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="https://th.bing.com/th/id/OIP.5BFnewK6zvkgRdnSydN4fAHaF1?w=196&h=180&c=7&r=0&o=5&dpr=1.5&pid=1.7" />
      </Head>
      <main className="flex min-h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col gap-12 p-4">
          <Topbar/>
          <NavBar/>
          {/* <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Welcome {session?.user?.name}
          </h1> */}
          <AboutComponent/>
          {/* {session ? (
            <Button onClick={() => signOut()} btnClass="btn-primary text-white uppercase" title="Sign out!"/>
          ) : (
            <Button onClick={() => signIn()} btnClass="btn-primary text-white uppercase" title="Sign in!"/>
          )} */}
        </div>
      </main>
    </>
  );
}
